### PR TITLE
AlertSqlGenerator Tab

### PR DESCRIPTION
**Pull request by Harwinder-VA**

### CODE REVIEW

**Review by Harwinder-VA — COMMENTED** [review]
- code commenting is pending.
- use pre written functions for ajax calling
- approving for testing purpose , resolve ASAP

**Review by Harwinder-VA — COMMENTED** [review]
Okay

**Review by Harwinder-VA — COMMENTED** [review]
okay

**Review by Amit-Vienna — APPROVED** [review]
fine

**Pull request merged**
